name: portfolio
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  # Scrollable list with positioned
  scrollable_positioned_list: ^0.3.8
 
  # Add animation with Lottie files
  lottie: ^3.0.0
 
  # Timeline view for Flutter
  timelines: ^0.1.0
  
  # Open URLs in mobile/web browsers
  url_launcher: ^6.2.4
  url_launcher_web: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/images/
    - assets/jsons/
    - assets/projects/

  # list giving the asset and other descriptors for the font.
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: Diphylleia
      fonts:
        - asset: assets/fonts/Diphylleia-Regular.ttf
    - family: MonomaniacOne
      fonts:
        - asset: assets/fonts/MonomaniacOne-Regular.ttf
    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    
